# Generated by Django 5.0.7 on 2024-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("suggestion", "Suggestion"),
                            ("compliment", "Compliment"),
                            ("complaint", "Complaint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "about_service",
                    models.CharField(
                        choices=[
                            ("enquiries", "Enquiries/Information"),
                            (
                                "complaint_handling",
                                "Complaint handling/dispute resolution",
                            ),
                            ("home_building", "Home building licenses"),
                            ("business_licenses", "Business licenses"),
                            ("inspections", "Inspections/Investigations"),
                            ("transport_bonds", "Transport/Travel bonds"),
                            ("strata_mediation", "Strata/State mediation"),
                            ("cooperatives", "Co-operatives/Associations"),
                            (
                                "asbestos",
                                "Loose-fill asbestos implementation taskforce",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "about_issue",
                    models.CharField(
                        choices=[
                            (
                                "fair_trading",
                                "Fair Trading decision, policy or procedure",
                            ),
                            ("administration", "Administration of legislation"),
                            ("information", "Information accuracy"),
                            ("timeliness", "Timeliness of service"),
                            ("staff", "Staff actions/Customer service"),
                            ("accessibility", "Accessibility of service"),
                            ("fees", "Fees/Charges"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_service",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "other_issue",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("how_provided", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "fair_trading_officer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_service", models.DateField(blank=True, null=True)),
                ("time_of_service", models.TimeField(blank=True, null=True)),
                ("trader_or_consumer", models.CharField(max_length=50)),
                ("feedback_details", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "organisation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "daytime_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
